<<<<<<< HEAD
# Generated by Django 2.2 on 2019-06-14 01:13
=======
# Generated by Django 2.2 on 2019-05-17 00:24
>>>>>>> 0d0e8fae891da611d3ccfcd27302027f40f3db3d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
<<<<<<< HEAD
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_image', models.URLField(blank=True, default='https://via.placeholder.com/150', null='True')),
=======
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TextField(blank=True, null=True)),
                ('event_image', models.ImageField(blank=True, default='https://via.placeholder.com/150', null='True', upload_to=None)),
>>>>>>> 0d0e8fae891da611d3ccfcd27302027f40f3db3d
            ],
        ),
    ]
