# Generated by Django 2.1.7 on 2019-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null='False'),
            preserve_default='False',
        ),
    ]
