# Generated by Django 2.1.7 on 2019-03-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190319_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='https://via.placeholder.com/150', upload_to=None),
        ),
    ]
