# Generated by Django 2.1.7 on 2019-03-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='https://via.placeholder.com/150', null='True', upload_to=None),
        ),
    ]
