# Generated by Django 2.1.7 on 2019-03-23 16:31

from django.db import migrations
from django.conf import settings
from django.contrib.auth import get_user_model

def create_beatles(apps, schema_editor):
    User = get_user_model()

    john = User(
        username="jon.doe@example.com",
        first_name="Jon",
        last_name="Doe",
        is_superuser=True,
        is_staff=True,
    )
    john.set_password("password")
    john.save()

    paul = User(
        username="jane.doe@example.com",
        first_name="Jane",
        last_name="Doe",
        is_staff=True,
    )
    paul.set_password("password")
    paul.save()

    ringo = User(
        username="mike.smith@example.com",
        first_name="Mike",
        last_name="Smith",
    )
    ringo.set_password("password")
    ringo.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.RunPython(create_beatles)
    ]
